---

- name: Remove generated earlier configs and flush db
  block:
    - name: "Stop {{ ton_node_service_name }} service"
      service:
        name: "{{ ton_node_service_name }}"
        state: stopped
    - name: Delete old configs and flush db
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ ton_rnode_config_dir }}/config.json"
        - "{{ ton_rnode_config_dir }}/console.json"
        - "{{ ton_rnode_config_dir }}/console_config.json"
        - "{{ ton_rnode_db_dir }}"
        - "{{ ton_node_src_dir }}/release"
        - "{{ ton_node_src_dir }}/ton_rnode"
